/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\boats0.2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boats0.2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[9.104, 0, -0.164]}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials['Master Pallet']} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials.House_Mat} />
      </group>
      <mesh geometry={nodes.Subrine.geometry} material={materials['Master Pallet']} position={[-2.152, 0, -1.458]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Master Pallet']} position={[2.021, 0.004, -3.161]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Master Pallet']} position={[5.8, 0.004, -3.161]} />
    </group>
  )
}

useGLTF.preload('/boats0.2.gltf')
