/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\boats0.2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Boat(props) {
  const { nodes, materials } = useGLTF('./models/boats0.2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials['Master Pallet']} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials.House_Mat} />
      </group>
      <mesh visible={false} geometry={nodes.Subrine.geometry} material={materials['Master Pallet']} position={[0, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh visible={false} geometry={nodes.Plane.geometry} material={materials['Master Pallet']} position={[0, 0, 0]} />
      <mesh visible={false} geometry={nodes.Plane001.geometry} material={materials['Master Pallet']} position={[5.8, 0.004, -3.161]} />
    </group>
  )
}

useGLTF.preload('./models/boats0.2.gltf')
