/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Models\prototype3.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Prototype3(props) {
  const { nodes, materials } = useGLTF('./models/prototype3.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-4, 4, -4]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-2, 2, -2]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.000']} />
    </group>
  )
}

useGLTF.preload('./models/prototype3.gltf')
